# Generated by Django 4.1.5 on 2023-01-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='latitude',
            field=models.TextField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='longitude',
            field=models.TextField(verbose_name='Longitude'),
        ),
    ]
