# Generated by Django 4.1.5 on 2023-01-07 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_memories', '0002_alter_memory_latitude_alter_memory_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='latitude',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[-+]?([1-8]?\\d(\\.\\d+)?|90(\\.0+)?)', 'Wrong coordinate')], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='longitude',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('\\s*[-+]?(180(\\.0+)?|((1[0-7]\\d)|([1-9]?\\d))(\\.\\d+)?)$', 'Wrong coordinate')], verbose_name='Longitude'),
        ),
    ]
