# Generated by Django 4.1.5 on 2023-01-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_memories', '0003_alter_memory_latitude_alter_memory_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='latitude',
            field=models.CharField(max_length=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='longitude',
            field=models.CharField(max_length=10, verbose_name='Longitude'),
        ),
    ]
